### ISSUE TITLE
Futile on Unity 5

### ISSUE THREAD

**Issue by diegodorado** [MattRix/Futile#235]
Hi MattRix. 
First off, thanx for your work, I apreciate it very much.

We were trying out our game project under Unity 5, and we had a couple of small issues with Futile.

First one was that all shortcut methods like renderer, rigidbody, etc were removed from Unity 5... but changing those calls to GetComponent\<Renderer\>() resolved it.

Next, and here I dont know how to resolve, is that by default Unity5 use full screen on android.
I normally do not listen for resize since i make games for android only and use a single orientation
And, by the time I can listenForResize, the FutileInit was already called.... 

I know I cant call Futile.Init again...Is there any reset method I could use to handle this?
Thank you

**Comment by MattRix** [comment]
Hmm, have you tried just delaying when the first Futile.Init is called?
That might be the easiest way to handle it.

**Comment by diegodorado** [comment]
Hey, thanks for the quick response.

I did, and it works... But I have to make a 3 seconds delay at least (tried with 1sec and 2sec, and screen was not yet resized).... and since I am using futile for showing a start page I would rather not make such a delay there.....

do you think that I could show a start page, and, on listenForResize, destroy the camera and call Futile.Init again?

**Comment by MattRix** [comment]
Hmm, yeah you could try something like that.

**Comment by diegodorado** [comment]
Thanxs, I'll try and tell you afterwards

2015-03-12 14:06 GMT-03:00 Matt Rix <notifications@github.com>:

> Hmm, yeah you could try something like that.
>
> On Wednesday, March 11, 2015, Diego Dorado <notifications@github.com>
> wrote:
>
> > Hey, thanks for the quick response.
> >
> > I did, and it works... But I have to make a 3 seconds delay at least
> > (tried with 1sec and 2sec, and screen was not yet resized).... and since
> I
> > am using futile for showing a start page I would rather not make such a
> > delay there.....
> >
> > do you think that I could show a start page, and, on listenForResize,
> > destroy the camera and call Futile.Init again?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/MattRix/Futile/issues/235#issuecomment-78301445>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattRix/Futile/issues/235#issuecomment-78529818>.
>



-- 
--
Diego Dorado
11 3758 3589

**Comment by simondorfman** [comment]
Hello, I'm new to Unity & Futile, starting development on a new game. I intend to get started with this tutorial: http://gamedevelopment.tutsplus.com/tutorials/how-to-match-puzzle-shapes-using-bitmasks--gamedev-11759

Would you suggest using Unity 5 or Unity 4?

Hope it's okay to post this question here. I didn't see a mailing list or forum devoted to Futile...

**Comment by diegodorado** [comment]
I would suggest to stick with unity 4.6.
Unity 5 doesnt play nice with Futile right now, so, unless you do need some
of the (few) unity5 features, do not upgrade and  you ll be fine

**Comment by jpsarda** [comment]
Unity 5 is a nice choice for a long term project, as it will be fixed in a couple of months but if you need to publish something soon with Futile, that's not a good choice ( example of problems I have with Unity 5 : http://www.reddit.com/r/futile/comments/32wwvv/unity_50x_app_freeze_in_nondevelopment_build_only/ )

**Comment by MattRix** [comment]
Which Unity 5 stuff doesn't work with Futile right now for you? If you have
issues with it, let me know, it should be working fine in Unity 5.

**Comment by jpsarda** [comment]
@MattRix I guess your question is addressed to @diegodorado ? To me the Unity 5 bug described in the link above is pretty serious for Futile (it seems to impact Android and mac but not iOS). And the bug report didn't even show up in the Unity recent bug report entries (in 10 days!). I really hope they can fix it for 5.0.2 or I'll have to go back to 4.6 (which I really don't want to).

**Comment by diegodorado** [comment]
Hi @MattRix ,
These are the issues with unity5:


   - all shortcut methods like renderer, rigidbody, etc were removed from
   Unity 5... but changing those calls to GetComponent() resolved it.
   - by default Unity5 use full screen on android

I normally do not listen for resize since i make games for android only and
use a single orientation
By the time I can listenForResize, the FutileInit was already called....

I dont remember well now what weird things occured if I tried to call
Futile.Init
again...

It would be nice a reset method for those cases... or maybe a
listenForFullScreen ... I really dont know what would be better

Thank you for Futile!





2015-04-27 10:22 GMT-03:00 Jean-Philippe SARDA <notifications@github.com>:

> @MattRix <https://github.com/MattRix> I guess your question is addressed
> to @diegodorado <https://github.com/diegodorado> ? To me the Unity 5 bug
> described in the link above is pretty serious for Futile (it seems to
> impact Android and mac but not iOS). And the bug report didn't even show up
> in the Unity recent bug report entries (in 10 days!). I really hope they
> can fix it for 5.0.2 or I'll have to go back to 4.6 (which I really don't
> want to).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MattRix/Futile/issues/235#issuecomment-96650805>.
>



-- 
--
Diego Dorado
11 3758 3589

**Comment by jpsarda** [comment]
Good news the bug I was talking about ( http://fogbugz.unity3d.com/default.asp?691241_5379kc81q4fjp7fc ) is in the hand of the resolution team!

**Comment by MattRix** [comment]
Futile is working fine on Unity 5 these days so I'm gonna close this.
